site_name: Taolijie轻兼职接口文档
pages:
- 概述: index.md
- 登陆注册: register.md
- 任务系统: quest.md
- 账户系统: acc.md
- 后台接口: admin.md
- 签名生成: sign.md
- 兼职: job.md
- 二手: sh.md
- 推荐: reco.md
- 字典: dict.md

theme: readthedocs
site_author: 王鸿飞
